# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-04 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('identity', models.CharField(max_length=20, verbose_name='身份')),
                ('face_token', models.CharField(max_length=100)),
            ],
        ),
    ]
